#write aprogram to input 8 numbers from the user and display all the unique number once
n=set()
a=int(input("enter the 1st numbers:"))
b=int(input("enter the 1st numbers:"))
c=int(input("enter the 1st numbers:"))
d=int(input("enter the 1st numbers:"))
e=int(input("enter the 1st numbers:"))
f=int(input("enter the 1st numbers:"))
g=int(input("enter the 1st numbers:"))
h=int(input("enter the 1st numbers:"))
n.add(a)
n.add(b)
n.add(c)
n.add(d)
n.add(e)
n.add(f)
n.add(g)
n.add(h)
print(n)